### ISSUE TITLE
Feature: support for `node:` prefixed URL-style imports

### ISSUE THREAD

**Issue by dominics** [FormidableLabs/trace-deps#75]
- https://github.com/nodejs/node/pull/37246

(supported in both CommonJS `require` and ESM `import`)

**Comment by ryan-roemer** [comment]
This should have already landed in `trace-deps@0.4.5` via https://github.com/FormidableLabs/trace-deps/pull/71

Is anything not working in CJS or ESM?

**Comment by dominics** [comment]
Apologies, I'll take a closer look at my dependency tree and get back to you shortly!

**Comment by ryan-roemer** [comment]
Thanks and no worries! It’s a really recent release

**Comment by dominics** [comment]
Yup, `yarn why` showed `0.4.0`! trace-deps wasn't in our dependency list, so it was only satisfying https://github.com/FormidableLabs/serverless-jetpack/blob/94147f7d57b00ab477efd5ee31fe40f221c1b09d/package.json#L49

A quick lockfile update later, and we're running `0.4.5`, which is coping with `node:crypto` well

Thanks for the work!
